### ISSUE TITLE
Documentation updates to do

### ISSUE THREAD

**Issue by naultran** [STRIDES-Codes/A-FAIR-Data-Collection-Tool-to-standardize-research-meta-data-collection#12]
- Can we link the term "schema" to the ISA readthedoc (https://isatools.readthedocs.io/en/latest/isamodel.html). 
- Can we put the figure in a seperate section named 'Overview of the tool'
- Below the text for "what does our problem solve", can we write. "Our tail aims to:" then bullet point the following (1) Facilitate metadata collection using a familiar user interface, (2) allow the portability of (meta)data entry to the data source, (3) Facilitate the upload of structured (meta)data to the cloud for easy sharing

Maybe we can mention that this is build surrounding the ISA framework which has a large suite of tools that can be used in conjunction with ours and link to isa-tools.org?

below installation, maybe we can add something like a walk-through? Do we know if we can embed a video?

**Comment by dalesusan1** [comment]
It looks like it is possible to embed a video, but we might have to upload it to Youtube first and just link it. I can certainly work on that if/once you have a screen recording done.
